# Generated by Django 4.2.1 on 2023-06-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('idcategoriaP', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionP', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=150)),
                ('precio', models.IntegerField()),
                ('file', models.ImageField(upload_to='IMG/Productos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaproducto')),
            ],
        ),
    ]
